name: donfra-local

services:
  # ===== UI: nginx + 静态 Next 导出站 + 反向代理 =====
  ui:
    build:
      context: ../donfra-ui 
    image: donfra-ui:dev
    # container_name 可以不写，让 compose 自己管理
    container_name: donfra-ui
    ports:
      - "80:80"                      # 浏览器访问 http://localhost
    depends_on:
      - api
      - ws
    networks:
      - donfra-local

  # ===== API: Go 后端 =====
  api:
    build:
      context: ../donfra-api         # 根据你实际路径改
    image: donfra-api:dev
    container_name: donfra-api
    environment:
      - ADDR=:8080
      - PASSCODE=7777               
      - ADMIN_PASS=7777
      - JWT_SECRET=don-secret
      - DATABASE_URL=postgres://donfra:arfnod@donfra-db:5432/donfra_study?sslmode=disable
      # - CORS_ORIGIN=http://localhost
      # - BASE_URL=http://localhost
    # expose:
    #   - "8080"
    ports:
      - "8080:8080"            
    depends_on:
      - donfra-db
    networks:
      - donfra-local

  # ===== WS: y-websocket 服务 =====
  ws:
    build:
      context: ../donfra-ws  
    image: donfra-ws:dev
    container_name: donfra-ws
    # expose:
    #   - "6789"
    environment:
      - ROOM_UPDATE_URL=http://api:8080/api/room/update-people
    ports:
      - "6789:6789"
    networks:
      - donfra-local

  donfra-db:
    image: postgres:16
    container_name: donfra-db
    environment:
      - POSTGRES_USER=donfra
      - POSTGRES_PASSWORD=arfnod
      - POSTGRES_DB=donfra_study
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/seed_lessons.sql:/docker-entrypoint-initdb.d/seed_lessons.sql:ro
    networks:
      - donfra-local

networks:
  donfra-local:
    driver: bridge

volumes:
  pgdata: {}
