apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: donfra
data:
  ADDR: ":8080"
  PASSCODE: "7777"
  ADMIN_PASS: "7777"
  DATABASE_URL: "postgres://donfra:arfnod@postgres:5432/donfra_study?sslmode=disable"
  JAEGER_ENDPOINT: "otel-collector:4318"
  REDIS_ADDR: "redis:6379"
  USE_REDIS: "true"
